In [1]:
import pandas as pd

# Reading Data

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

        fever  Body Pain   age  runnyNose  difficulty breath  infection prob
0  101.237282        0.0  47.0        0.0                1.0             1.0
1   99.661903        0.0  28.0        0.0                0.0             0.0
2   98.640465        1.0   0.0        1.0               -1.0             1.0
3   99.239645        0.0  28.0        0.0                0.0             0.0
4  101.076366        1.0  32.0        0.0               -1.0             1.0

In [5]:
df['difficulty breath'].value_counts()

 0.0    1837
-1.0     472
 1.0     459
Name: difficulty breath, dtype: int64

In [6]:
df.describe()

,fever,Body Pain,age,runnyNose,difficulty breath,infection prob
count,2778.000000,2768.000000,2768.000000,2768.000000,2768.000000,2768.000000
mean,100.015897,0.250000,38.575867,0.254697,-0.004697,0.253974
std,1.166268,0.433091,23.238025,0.435769,0.580037,0.435362
min,98.000028,0.000000,0.000000,0.000000,-1.000000,0.000000
25%,98.996770,0.000000,28.000000,0.000000,0.000000,0.000000
50%,100.002163,0.000000,28.000000,0.000000,0.000000,0.000000
75%,101.053187,0.250000,49.000000,1.000000,0.000000,1.000000
max,101.997625,1.000000,100.000000,1.000000,1.000000,1.000000

# Train Test Splitting

In [7]:
import numpy as np

In [9]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [60]:
np.random.permutation(7)

array([4, 0, 1, 2, 6, 5, 3])

In [61]:
train,test=data_split(df,0.2)

In [62]:
train

,fever,Body Pain,age,runnyNose,difficulty breath,infection prob
315,101.169338,0.0,28.0,0.0,0.0,0.0
610,98.337130,0.0,86.0,1.0,0.0,0.0
2451,100.656593,0.0,28.0,0.0,0.0,0.0
2266,100.957753,0.0,15.0,1.0,0.0,0.0
2398,101.477909,1.0,30.0,1.0,-1.0,0.0
...,...,...,...,...,...,...
1638,99.926307,0.0,71.0,0.0,-1.0,1.0
1095,100.977505,0.0,28.0,0.0,0.0,0.0
1130,99.167471,0.0,88.0,0.0,-1.0,1.0
1294,100.554546,0.0,56.0,1.0,0.0,1.0
860,100.032554,0.0,30.0,0.0,0.0,1.0

In [63]:
test

,fever,Body Pain,age,runnyNose,difficulty breath,infection prob
879,100.213708,0.0,28.0,0.0,0.0,0.0
1990,99.565413,1.0,58.0,0.0,1.0,0.0
889,101.289094,0.0,28.0,0.0,0.0,0.0
912,98.407762,0.0,61.0,0.0,-1.0,1.0
2633,101.509863,0.0,28.0,0.0,0.0,0.0
...,...,...,...,...,...,...
238,100.925361,1.0,38.0,0.0,-1.0,1.0
1980,98.156029,0.0,61.0,1.0,1.0,0.0
1950,99.641789,1.0,21.0,0.0,-1.0,0.0
1702,99.203829,1.0,85.0,1.0,1.0,1.0
100,98.266676,1.0,18.0,1.0,0.0,1.0

In [64]:
X_train = train[['fever','Body Pain','age','runnyNose','difficulty breath']].to_numpy()
X_test = test[['fever','Body Pain','age','runnyNose','difficulty breath']].to_numpy()

In [70]:
Y_train = train[['infection prob']].to_numpy().reshape(2225 ,)
Y_test = test[['infection prob']].to_numpy().reshape(556 ,)

ValueError: cannot reshape array of size 2223 into shape (2225,)

In [66]:
Y_train

array([0., 0., 0., ..., 1., 1., 1.])

In [67]:
from sklearn.linear_model import LogisticRegression

In [69]:
clf=LogisticRegression()
clf.fit(X_train, Y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').